lang: pt-br
project:
  type: website
  output-dir: docs
   

website:
  page-navigation: true
  title: "Pesquisa Quantitativa"
  repo-url: https://github.com/pablo-huascar/pesquisa_quanti_psi_ufc
  repo-branch: main
  page-footer:
    left: "Esta página foi construída com [Quarto](https://quarto.org/)."
    right: 
      <img src="img/brasao1_horizontal_cor_300dpi.png" width="200"> 
  navbar:
    align: center
    title: "Pesquisa Quantitativa"
    background: "#FDFEFE"
    search: true
    collapse-below: lg

    left:
      - text: "Proposta"
        file: index.qmd
      - text: "Conteúdos"
        file: conteudos.qmd      

    right: 
      - icon: "{{< fa brands github >}}"
        href: https://github.com/pablo-huascar/pesquisa_quanti_psi_ufc
      - text: "{{< fa brands github size=2x >}}"
        href: https://github.com/pablo-huascar/pesquisa_quanti_psi_ufc
      
        
  
  sidebar:
    - id: conteudos
      title: "Conteúdos"
      style: "floating"
      align: left
      contents:
        - href: conteudos.qmd
        - href: intro-r.qmd
        - href: exploracao-dados.qmd
        - href: inferencia-estatistica.qmd
        - href: regressao.qmd
   
format:
  html:
    code-link: true
    code-line-numbers: false
    code-tools: true
    code-copy: true
    theme: 
      - cosmo
      - styles.css
    toc: true
    link-external-icon: true
    link-external-newwindow: true

editor: visual
csl: apa.csl
