---
title: "org_banco_empatia"
format: html
editor_options: 
  chunk_output_type: console
eval: false
---

```{r}
#| eval: false
#| label: setup
 
library(tidyverse)
library(janitor)
library(haven)
library(readxl)
library(careless)
library(gt)
library(lavaan)
library(EGAnet)
```

```{r}
#| eval: false
df <- read_spss("data/empatia.sav") |> 
  clean_names()

itens <- read_excel("data/formulario_empatia.xlsx")
```

## Escala de Racismo Moderno

```{r}
#| eval: false
racismo <- df |> 
  select(r1:r14, sexo:estado_civil) |> 
  mutate(
    across(where(is.labelled), as_factor)
  )
```

```{r}
racismo |> 
  write_csv("data/dados_racismo_moderno.csv")
```

```{r}
#| eval: false
itens_racismo <- itens |> 
  select(`Eles têm conseguido mais do que merecem`:`Possuem uma beleza diferente`) |> 
  names() |> 
  tibble(Item = _) 
```

```{r}
#| eval: false
variaveis_racismo <- racismo |> 
  select(r1:r14) |> 
  names() |> 
  tibble(Variável = _)
```

```{r}
fator_racismo <- tibble(
  Fator = c(rep("Negação do preconceito", 7),
            rep("Afirmação das diferenças", 3),
            rep("Negação do preconceito", 2),
            rep("Afirmação das diferenças", 2))
)
```

```{r}
variaveis_racismo |> 
  bind_cols(itens_racismo) |> 
  bind_cols(fator_racismo) |> 
  write_csv("data/code_book_escala_racismo_moderno.csv")
```

```{r}
variaveis_demo <- racismo |> 
  select(sexo:area_de_formacao) |> 
  names() |> 
  tibble(Variáveis = _)
```

```{r}
descricao_demo <- tribble(
  ~Descrição,
  "Sexo",
  "Idade",
  "Renda per capita",
  "Cor/Raça",
  "Estado civil",
  "Área de formação"
)
```

```{r}
variaveis_demo |> 
  bind_cols(descricao_demo)
```

## Escala de Afetos

```{r}
df |> 
  select(a1:a20, sexo:estado_civil) |> 
  mutate(
    across(where(is.labelled), as_factor)
  ) |> 
  write_csv("data/dados_afetos_positivos_negativos.csv")
```

```{r}
afetos <- df |> 
  select(a1:a20)

EGAnet::EGA(afetos)

efa(afetos, nfactors = 2) |> 
  summary(cutoff = 0.4)
```

```{r}
#| eval: false
itens_afetos <- itens |> 
  select(`Muitas vezes, eu fico nervoso.`:`Tenho me sentido triste ultimamente.`) |>   names() |> 
  tibble(Item = _) 
```

```{r}
#| eval: false
variaveis_afetos <- df |> 
  select(a1:a20) |> 
  names() |> 
  tibble(Variável = _)
```

```{r}
fator_afetos <- tibble(
  Fator = c(
    "Afeto negativo",  # Muitas vezes, eu fico nervoso.
    "Afeto positivo",  # Me sinto confiante no dia a dia.
    "Afeto positivo",  # Sou corajoso.
    "Afeto negativo",  # Tenho me sentido cansado nos últimos meses.
    "Afeto negativo",  # Ando muito preocupado nos últimos tempos.
    "Afeto positivo",  # Sou determinado para conseguir o que eu quero.
    "Afeto negativo",  # Me sinto culpado por coisas que eu fiz no passado.
    "Afeto positivo",  # Sou apaixonado por algumas coisas que eu faço.
    "Afeto positivo",  # Muitas situações me deixaram alegre nos últimos tempos.
    "Afeto negativo",  # Fico zangado quando sou contrariado.
    "Afeto negativo",  # As pessoas dizem que sou mal-humorado.
    "Afeto negativo",  # Ultimamente ocorreram situações em que senti muita raiva de algumas pessoas.
    "Afeto positivo",  # Em geral eu me sinto forte para superar as dificuldades da vida.
    "Afeto positivo",  # Me dá prazer experimentar coisas novas.
    "Afeto positivo",  # Sinto orgulho de mim mesmo.
    "Afeto negativo",  # Eu me irrito facilmente.
    "Afeto positivo",  # Sou valente quando estou diante de um desafio.
    "Afeto positivo",  # Sou uma pessoa feliz.
    "Afeto negativo",  # Nos últimos tempos ocorreram situações em que me senti humilhado.
    "Afeto negativo"   # Tenho me sentido triste ultimamente.
  )
)
```

```{r}
variaveis_afetos |> 
  bind_cols(itens_afetos) |> 
  bind_cols(fator_afetos) |> 
  write_csv("data/code_book_escala_afetos_positivos_negativos.csv")
```
